services:
  db:
    image: postgres:17
    container_name: canchaYa_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbCanchaYa
    volumes:
      - ./backend/.volumes/postgres/data:/var/lib/postgresql/data/
      - ./backend/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: container_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    links:
      - db

  frontend:
    build: ./frontend
    container_name: container_frontend
    ports:
      - "8080:80"
    links:
      - backend