services:
  db:
    image: postgres:17
    container_name: canchaYa_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbCanchaYa
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"